### PR TITLE
Return stuff from blocks. Deliberately leaks PHI (as per #17)

### LINKED ISSUE #17: Allow one-off blocks
To extract PHI in a single location, once blocks are available we should capture the result of the block and return it, to allow constructs like this:

```ruby
field_val = obj.allow_phi { obj.phi_field }
```

If we don't want to allow this sort of behavior (which I could see, since it explicitly "leaks" PHI to an uncontrolled location), we probably don't want blocks at all. Note that such "leaking" is already very easy to do, so this shouldn't be our only reason for not wanting this construct, e.g. 

```ruby
unprotected_data = []
obj.allow_phi!
unprotected_data << obj.phi_field
obj.disallow_phi!
```

### PR DESCRIPTION
**Pull request by Crisfole**
Fixes #17. Makes some constructs, especially in unit tests, much easiser.

### CODE REVIEW

**Comment by Crisfole** [comment]
This needs debate and discussion. It's not necessarily a good idea.

**Comment by wkirby** [comment]
@Crisfole I don't like this, and the reason is ruby default returns. You can imagine this scenario:

```
def foo
  bar.allow_phi(user, "phi access") do
      do_thing_with_phi(bar.phi_field)
  end
end
```

If `do_thing_with_phi` returns the passed in value, now `foo` _also_ returns PHI, which seems leaky.

I still think we're much better served by providing an explicit `get_phi` method if we want a way to escape PHI outside a block.

**Comment by Crisfole** [comment]
Sure. Good reason.

**Comment by Crisfole** [comment]
@wkirby I just moved the method into a `get_phi` I still like the syntax of using a block for extracting a single value. It also discourages using it heavily since it's a massively painful way to get more than one thing.

**Review by egreer — APPROVED** [review]
I think the updated format solves the concerns we had.

**Pull request merged**
